export enum USER_ROlES {
  PROVINCIAL_GOVERNMENT = 'PROVINCIAL_GOVERNMENT',
  MUNICIPALITY = 'MUNICIPALITY',
  SUPER_ADMIN = 'SUPER_ADMIN',
  WAREHOUSE = 'WAREHOUSE',
  STATION = 'STATION',
  COMPANY = 'COMPANY',
  DRIVER = 'DRIVER',
  CLIENT = 'CLIENT',
  ADMIN = 'ADMIN',
}

export enum USER_GENDERS {
  UN_NONE = 'UN_NONE',
  FEMALE = 'FEMALE',
  OTHER = 'OTHER',
  MALE = 'MALE',
}
